# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubModule_Use_Bundle-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SubModule_Use_Bundle-Example
  pod 'SubModule_Use_Bundle', :path => '../'

  target 'SubModule_Use_Bundle-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SubModule_Use_Bundle-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
