# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubModule-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SubModule-Example
  pod 'SubModule', :path => '../'

  target 'SubModule-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SubModule-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
